### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by cakegod** [poma/PoeHorticraftingScanner#1]
No matter what I do, I keep getting "UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'matchAll' of undefined".

**Comment by poma** [comment]
Oh, looks like I din't upload a fix yet. This happens when you have an empty station in your stash. Try removing empty stations from and running script again just to verify, I'll upload the fix shortly

**Comment by poma** [comment]
fixed in 9afde695661d62b4b21b57a5ed58da933c8c903d
