### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by cakegod** [poma/PoeHorticraftingScanner#3]
> C:\Users\cakem\Documents\GitHub\PoeHorticraftingScanner>npm run short
(node:3696) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at stringToCraft (C:\Users\cakem\Documents\GitHub\PoeHorticraftingScanner\PoeHorticraftingScanner.js:87:34)
    at C:\Users\cakem\Documents\GitHub\PoeHorticraftingScanner\PoeHorticraftingScanner.js:159:65
    at Array.map (<anonymous>)
    at main (C:\Users\cakem\Documents\GitHub\PoeHorticraftingScanner\PoeHorticraftingScanner.js:159:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by poma** [comment]
Hmmm, looks like there is a mod that starts with `Change ` that is not convert resistance from X to Y

Any ideas what can that be?

**Comment by poma** [comment]
Oh I see, there are multiple of those, give me 10 min, will fix
